name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Build
        run: |
          npm install
          npm run build
        env:
          LTC_BASEPATH: '/client'
