name: Build

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '11.x'

      - run: npm install
      - run: npm run build

      - name: Release zip
        run: |
          rm -rf release.tar.gz
          touch release.tar.gz
          tar --exclude=release.tar.gz -zcf release.tar.gz * .env.sample
        env:
          LTC_BASEPATH: '/client'
